BEGIN;
-- Dedicated PostgreSQL database only. No runtime credentials or user data.
CREATE TABLE IF NOT EXISTS activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    device_name TEXT NOT NULL,
    platform TEXT NOT NULL,
    app_id TEXT NOT NULL,
    app_name TEXT NOT NULL,
    window_title TEXT DEFAULT '',
    display_title TEXT DEFAULT '',
    title_hash TEXT NOT NULL DEFAULT '',
    time_bucket INTEGER NOT NULL DEFAULT 0,
    started_at TEXT NOT NULL,
    created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
  );

CREATE UNIQUE INDEX IF NOT EXISTS idx_dedup
  ON activities(device_id, app_id, title_hash, time_bucket);

CREATE INDEX IF NOT EXISTS idx_activities_device_started
  ON activities(device_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_activities_started
  ON activities(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_activities_created
  ON activities(created_at);

CREATE TABLE IF NOT EXISTS device_states (
    device_id TEXT PRIMARY KEY,
    device_name TEXT NOT NULL,
    platform TEXT NOT NULL,
    app_id TEXT NOT NULL,
    app_name TEXT NOT NULL,
    window_title TEXT DEFAULT '',
    display_title TEXT DEFAULT '',
    last_seen_at TEXT NOT NULL,
    is_online INTEGER DEFAULT 1,
    extra TEXT DEFAULT '{}'
  );

CREATE TABLE IF NOT EXISTS health_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    type TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    recorded_at TEXT NOT NULL,
    end_time TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE(device_id, type, recorded_at, end_time)
  );

CREATE INDEX IF NOT EXISTS idx_health_records_recorded
  ON health_records(recorded_at);

CREATE INDEX IF NOT EXISTS idx_health_records_type
  ON health_records(type, recorded_at);

CREATE INDEX IF NOT EXISTS idx_health_records_device_recorded
  ON health_records(device_id, recorded_at);

CREATE TABLE IF NOT EXISTS device_consents (
    device_id TEXT PRIMARY KEY,
    consent_version INTEGER NOT NULL DEFAULT 1,
    activity_reporting INTEGER NOT NULL DEFAULT 0,
    health_reporting INTEGER NOT NULL DEFAULT 0,
    granted_scopes TEXT NOT NULL DEFAULT '[]',
    granted_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

CREATE TABLE IF NOT EXISTS visitor_heartbeats (visitor_key TEXT PRIMARY KEY, last_seen BIGINT NOT NULL);

CREATE INDEX IF NOT EXISTS idx_visitors_last_seen ON visitor_heartbeats(last_seen);

CREATE TABLE IF NOT EXISTS maintenance_state (name TEXT PRIMARY KEY, last_run_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS site_preferences (name TEXT PRIMARY KEY, value TEXT NOT NULL);

COMMIT;
